### PR TITLE
DM-23031: Create dipole separation functor

### PR DESCRIPTION
**Pull request by morriscb**
Create pixelScale unittest

Debug unittest

Compare to afw WCS pixel scale.

Adjust tolerence test.

### CODE REVIEW

**Comment by TallJimbo** [comment]
Oh, I should add that I'm pretty certain `SkyWcs.getPixelScale` *does* get the sin(dec) part right, so if your test against that passes for widely different dec values, you can rest easy about that part.

**Comment by morriscb** [comment]
> It's hard for me to evaluate whether this is correct without knowing what `base_LocalWcs_CDMatrix` is - if that is an affine approximation of the mapping from the pixel coordinates of the measurement image to a local gnomonic projection with angular-unit pixels, centered at the position of the object, then I think it's correct in the limit that the transformation between those two frames is just scale and rotation, not shear (i.e. as long as a distance in x is the same on the sky as a distance in y - I think this is a reasonable assumption anywhere on any of our coadds, but I'm not so sure about single-visit images near the edge of the focal plane).
> 
> To unpack that a bit, I said "local gnomonic projection with angular-unit pixels" instead of just "sky" because that's one a way to get the sin(dec) part right in those matrix elements, and I'm guessing from the "LocalWcs" nomenclature that this is what you actually did - apologies if I once knew and just forgot.

It's straight from the getCDMatrix method after getting a TANWcs at the objects coordinate. You can check out the code here: https://github.com/lsst/meas_base/blob/27e4659cd5023e8322ef7898a1568491f2b23f57/python/lsst/meas/base/plugins.py#L498

**Comment by morriscb** [comment]
I've checked the SkyOrigin on the Wcs and the declination is +53. I then tried other declination values and tests still passed. @TallJimbo if you could have one last look at the math, keeping in mind that I'm using the `SkyWcs.getCdMatrix(Point2D)`. Looking at the SkyWcs code this is the same CdMatrix call that is used when calling `getTanWcs` so hopefully the math is working the way I think it is.

**Comment by TallJimbo** [comment]
Huh. `SkyWcs.getCdMatrix` with a position argument is something I don't really understand the utility of - it apparently evaluates the Jacobian of the transformation from pixels to "intermediate world coordinates", which is a fairly arbitrary FITS WCS concept.  For a simple TAN WCS that would mean you'll get the right answer as long as you aren't too far away from the projection point (tract or visit center), but I don't know what "too far" means.  I'm thinking we should merge this ticket and open a new one to rewrite the LocalWcs logic to avoid calling `getCdMatrix` (and maybe even remove the variant of that that takes a position, as I think it's dangerous).

**Comment by timj** [comment]
Naively, it seems to me that SkyWcs.getCdMatrix can't ever work reliably if you have large distortions in your WCS. The reason we are using complex WCS transformations is precisely because a CD matrix is not good enough.

**Comment by morriscb** [comment]
@TallJimbo okay, I'll merge this. However, for the SDM we still need some sort of local (at the point the object) approximation of the WCS that is store-able in the catalog. `getTanWcs`, which relies on `getCdMatrix`, seemed to be the way to do this. Is there another option currently given the Wcs methods available?

**Comment by TallJimbo** [comment]
I think something based on `SkyWcs.linearizePixelToSky` would be safe.  Probably not on its own; I think we'd at least need to multiply that matrix by either `sin(dec)` or `cos(dec)`, and maybe a bit more than that, but that method would include all of the nontrivial stuff (I just haven't worked through the details of what the trivial stuff would be).

**Pull request merged**
