### PR TITLE
DM-32756: Compute average FWHM of the PSF on an exposure as the media…

### PR DESCRIPTION
**Pull request by surhudm**
…n of PSF determined on a grid of points

### CODE REVIEW

**Comment by ktlim** [comment]
Commit comments don't usually need to include the ticket number; the PR title is sufficient.  Commit comments should also be under 50 characters: https://developer.lsst.io/work/flow.html#writing-commit-summary-lines

**Comment by arunkannawadi** [comment]
Changing the base to a corresponding ticket branch within `lsst` so we can test this more thoroughly and merge it to `main`. Thanks @surhudm !

**Comment by isullivan** [comment]
Note that these changes need to be made in `lsst.ip.diffim.subtractImages` now, instead of in `pipe_tasks`

**Comment by arunkannawadi** [comment]
Thanks Ian! ... I'll look at the refactoring that happened since these changes were made. Alternatively, I'd appreciate if we can paircode this ticket.

**Pull request merged**
