### PR TITLE
DM-40826: Remove deprecated redirects

### PR DESCRIPTION
**Pull request by mwittgen**

### CODE REVIEW

**Comment by mwittgen** [comment]
Jenkins passed: https://rubin-ci.slac.stanford.edu/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/2643/pipeline

**Comment by arunkannawadi** [comment]
There's quite a bit more to remove - these lines in test_import.py and the files that are listed here: https://github.com/lsst/pipe_tasks/blob/82031d62a58d2c836db5f787bf3502244a7c425c/tests/test_import.py#L39-L45

**Comment by arunkannawadi** [comment]
Alternatively,aAn org-wide search of the ticket number should give you the files and lines to be removed.

**Review by arunkannawadi — APPROVED** [review]
I'd remove lines 39-45 in test_import.py. Otherwise, LGTM!

**Review by arunkannawadi — APPROVED** [review]

**Comment by arunkannawadi** [comment]
Oh wait, the other files are not removed now after the latest force push

**Comment by mwittgen** [comment]
Sorry, wrong push, fixed now.

**Review by arunkannawadi — APPROVED** [review]

**Pull request merged**
